
name: Update Dependencies

on:
  repository_dispatch:
    types: [ updatedeps ]

jobs:
  UpdateDep:
    name: Update Dependency
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go environment
      uses: actions/setup-go@v1
      with:
        go-version: 1.18 # optional
    - name: Update Dependency
      run: |
        echo ${{ github.event.client_payload.tag }}
        go get -u -v github.com/wechaty/go-wechaty@${{ github.event.client_payload.tag }}
