name: Send Dispatch

on:
  push:
    tags:
      - '*'


jobs:
  send:
    name: Send Dispatch
    runs-on: ubuntu-latest
    steps:

    # Dispatch to update go-wechaty-getting-started deps.
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1.1.1
      with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: dchaofei/test-dispatch-source
          event-type: updatedeps
          client-payload: '{"tag":${{ github.ref_name }}}'

